### ISSUE TITLE
Build not working on Mac 10.11 / XCode 7.3 

### ISSUE THREAD

**Issue by harpreets** [TatsuyaOGth/ofxEyeTribe#3]
I'm on 
_openFrameworks of_v0.9.3_osx_release_, 
_XCode 7.3_, 
_OSX 10.11_, 
Boost (1.59) installed via homebrew,
_Eye Tribe Hardware Model: ET1000_

Created the project via projectgenerator, added the header/library search paths, linked binary with libraries libGazeApiLib.a, libboost_system.a, libboost_thread.a 
Tried to build both on Debug/Release for Mac 64-bit arch but getting build errors as follows:

<img src="http://i.imgur.com/NFaEZP7.jpg"/>

Did I miss installing anything or linking any dependencies?

**Comment by AndreasRef** [comment]
I get the same error...

**Comment by TatsuyaOGth** [comment]
I pushed next version for supporting oF0.9x to https://github.com/TatsuyaOGth/ofxEyeTribe/tree/release/v09x_reconst_lib_for_osx

However, I couldn't test that version because my Eye Tribe device was broken. please pull or download from above branch, and test with your EyeTribe.
Thank you!

**Comment by AndreasRef** [comment]
I still get the same error...
<img width="1512" alt="screen shot 2016-08-29 at 23 10 23" src="https://cloud.githubusercontent.com/assets/9645568/18067619/d73a8bba-6e3d-11e6-9eeb-0397f02dd8db.png">

**Comment by TatsuyaOGth** [comment]
seems like "GazeApiLib.a" is linking to your xcode project. isn't it?

Please unlink the library, and add the API's source files to compile list. these are located in  "ofxEyeTribe/libs/EyeTribeCppClient/src". 

please check README on https://github.com/TatsuyaOGth/ofxEyeTribe/tree/release/v09x_reconst_lib_for_osx

**Comment by AndreasRef** [comment]
I am very new to OpenFrameworks, so you may very well be right. I must admit that I don't know how to unlink a library?

Regarding the README and step 3:
Where do I find the "Build settings" inside XCode? 

Again sorry, I am quite new to openFrameworks (and sometimes wishing me back to Processing ;-))

**Comment by TatsuyaOGth** [comment]
ok, see this gif. 
![build_settings](https://cloud.githubusercontent.com/assets/1717663/18098338/d4c72d86-6f1c-11e6-8e89-36af9799d268.gif)

**Comment by AndreasRef** [comment]
Sorry for my late response, and thanks a lot for helping out!

So this is what my header search path looks like now. 

![screen shot 2016-10-27 at 12 02 29](https://cloud.githubusercontent.com/assets/9645568/19763320/cfe8e90a-9c3d-11e6-8deb-85b30d75a5df.png)

And I unlinked the GazeApiLib.a from "Other Linker Flags". 

![screen shot 2016-10-27 at 12 10 33](https://cloud.githubusercontent.com/assets/9645568/19763482/7949a19c-9c3e-11e6-96d2-b5daee206c8e.png)

What do you mean by "and add the API's source files to compile list"? How do I do that?

**Comment by RichardAW** [comment]
Hello I am also having trouble getting this add on to run on OF 0.9.8. I've installed Boost adding the boost path BOOST_PATH = /usr/local/Cellar/boost/1.63.0 and added the header and linker flags though i still can't seem to find the boost libraries. Any ideas?? 

<img width="1400" alt="screen shot 2017-01-01 at 08 57 09" src="https://cloud.githubusercontent.com/assets/17881897/21580648/c6e3afca-cfff-11e6-8ef0-5815a44ba80b.png">

<img width="1404" alt="screen shot 2017-01-01 at 08 56 02" src="https://cloud.githubusercontent.com/assets/17881897/21580647/a239ea54-cfff-11e6-9833-a789d60b9a7d.png">

**Comment by TatsuyaOGth** [comment]
hmm... ok, current version seems has some problems. I will try to reconstruction this codes. Give me time to do that (or give me any ideas)

**Comment by RichardAW** [comment]
Thanks that would be amazing.. I can have a tinker too no problem. Unfortunately i'm not sure I understand the process enough to me much help. I find these kinds of problems tricky to get my head around unfortunately. A good learning exercise for me though!

**Comment by ryohajika** [comment]
On my creation process with this wonderful addon, I got be stuck in the same situation on the same development environment... My method, which I could conquer the problem, is to use ofxOSXBoost (https://github.com/danoli3/ofxOSXBoost) instead of installing boost library via homebrew or using pre-compiled library. I think you guys don't need to know this anymore, but hope this info will be useful for our next step:)
